linters-settings:
  goimports:
    local-prefixes: github.com/hebertsanto/enube-challenge
  unused:
    check-exported: true

linters:
  enable:
    - goimports
    - unused
    - govet
    - errcheck
    - staticcheck
    - gofmt