name: CI

on:
  push:
    branches: ["main", "dev"]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: ["main", "dev"]
    paths-ignore:
      - '**/*.md'
      
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.0
    - name: Install dependencies
      run: go mod tidy
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - name: Run golangci-lint
      run: golangci-lint run

